default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: lap_notetaker_development

test:
  <<: *default
  database: _test

production:
  database: deploy
  <<: *default
